package scanner;

public enum TokenType 
{
	LEFTBRACKET, RIGHTBRACKET, LEFTCURLY, RIGHTCURLY, 
	COMMA, COLON, SEMICOLON, LEFTPAREN, RIGHTPAREN, 
	AND, OR, MULT, DIV, ADD, MINUS, EQUAL, LESSEQ, 
	GREATEQ, LESSER, GREATER, ASSIGN, NOTEQUAL, 
	DOUBLETICK, SINGLETICK, PERIOD, COMMENTS, MOD,
	NONTERM, EXIT, NULL, NONE, GRAMMAREQ, 
	
	WORKSPACE, ENDWORKSPACE, CLASS, ENDCLASS, NEW, ELSE, ELSEIF, ENDELSE, ENDELSEIF, SET, GET, ENDSET, ENDGET,
	PROP, ENDPROP, RETURN, INT, DOUBLE, FLOAT, BYTE, CHAR, STRING, BOOL, PRIVATE, STATIC, PUBLIC, PROTECTED, INCLUDES, 
	IMPLEMENTS, CON, ENDCON, VOID, FUNC, ENDFUNC, SWITCH, ENDSWITCH, CASE, FOR, ENDFOR, WHILE, ENDWHILE, INTLIT, STRLIT, NIL
}
